name: CI on Push and Pull Request

on: [push, pull_request]

jobs:
  Android:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2.5.0
    - name: Android
      run: |
        nuget restore
        cd MedikTapp.Android
        msbuild MedikTapp.Android.csproj /verbosity:normal /t:Rebuild /p:Configuration=Release
        
  #iOS:
    #runs-on: macos-latest
    #steps:
    #- uses: actions/checkout@v1
    #- name: iOS
      #run: |
        #nuget restore
        #msbuild MedikTapp.iOS.csproj /verbosity:normal /t:Rebuild /p:Platform=iPhoneSimulator /p:Configuration=Release
