name: Build Xamarin.Android app

on: [push]

jobs:
  build:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v3.0.1

    - name: Setup .NET Core SDK 6.0.x
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'

    - name: Install dependencies
      run: nuget restore

    - name: Build
      run: msbuild MedikTapp/MedikTapp.Android.csproj /t:PackageForAndroid /p:Configuration=Release