on: push

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2.4.2
      
    - name: Setup Android signing 
      run: (echo ${{ secrets.KEYSTORE }} | base64 — decode) > */MedikTapp.Android/MedikTapp.jks
      
    - name: Set Android version
      uses: damienaicheh/update-android-version-manifest-action@v1.0.0
      with:
        android-manifest-path: ./GitHubActions.Android/Properties/AndroidManifest.xml
        version-name: ${{ secrets.APP_VERSION }}
        version-code: ${{ github.run_number }}
        
    - name: Restore NuGet packages
      run: nuget restore
      
    - name: Build Android
      run: MSBuild /t:SignAndroidPackage /p:Configuration=Release /p:AndroidPackageFormat=apk /p:AndroidKeyStore=true /p:AndroidSigningKeyAlias=githubactionsxamarin /p:AndroidSigningKeyPass=${{ secrets.KEYSTORE_PASSWORD }} /p:AndroidSigningKeyStore=MedikTapp.jks /p:AndroidSigningStorePass=${{ secrets.KEYSTORE_PASSWORD }} ./MedikTapp.Android/MedikTapp.Android.csproj
